### ISSUE TITLE
Room size limit can be altered

### ISSUE THREAD

**Issue by BenSnellgrove** [wsun/multibuzzer#57]
By POSTing to the `/games/${Buzzer.name}/create` endpoint directly, a payload with a room size of values other than the default (200) can be given, accepted and used.

## Example:
Room size of 5000
### Target:
`https://www.multibuzz.app/games/buzzer/create`
### Payload:
```json
{"numPlayers":5000}
```
### Result:
![image](https://github.com/user-attachments/assets/9381ef65-4ea1-4e85-a868-2e9f79a13cb7)

Reasonable values over 200 do not seem to cause crashes
- Room creation becomes slow
- Server performance for other users creating/using rooms does not seem impacted
- Creating very large rooms (eg. 100000000) returns a heroku server error

Values under 200 and above 0 cause no issue
- Could be a useful feature for creating smaller rooms

Setting capacity at 0 creates a room of size 1
Values under 0 return internal server error

My guess is that this is all handled by boardgame.io, or whoever owns the "axios" library, as I'm talking directly to the creation endpoint, and as such this is not something you can fix in this repo. Thought I'd submit this anyway

**Comment by wsun** [comment]
Thanks for taking the time to share this! I took a look - yes this is managed by boardgame.io. Since I'm running multibuzz.app on a cheap machine that may not be able to handle arbitrarily large rooms, I've updated my fork of the library to prevent large rooms from being created directly from the endpoint.
